version: 2
updates:
- package-ecosystem: nuget
  directory: "/Solutions"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: YamlDotNet
    versions:
    - 10.0.0
    - 11.0.1
    - 11.1.0
    - 9.1.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: SpecFlow.Tools.MsBuild.Generation
    versions:
    - 3.6.23
    - 3.7.13
  - dependency-name: SpecFlow
    versions:
    - 3.6.23
    - 3.7.13
  - dependency-name: SpecFlow.NUnit
    versions:
    - 3.6.23
    - 3.7.13
  - dependency-name: coverlet.msbuild
    versions:
    - 3.0.2
